linters:
  enable:
    # Code Correctness
    - bodyclose        # Ensures HTTP response bodies are closed
    - contextcheck     # Checks proper usage of context.Context
    - errcheck         # Checks error handling
    - errorlint        # Validates error handling patterns
    - exhaustive       # Verifies switch statement completeness
    - govet            # Reports suspicious constructs
    - ineffassign      # Detects ineffective assignments
    - nilerr           # Checks for incorrect handling of nil errors
    - nilnil           # Detects redundant nil checks
    - noctx            # Finds improper use of background context
    - prealloc         # Suggests preallocating slices
    - rowserrcheck     # Ensures database rows and statements are checked for errors
    - sqlclosecheck    # Ensures database rows and statements are closed
    - staticcheck      # Comprehensive static analyzer
    - typecheck        # Checks type correctness
    - unused           # Finds unused code

    # Code Quality
    - cyclop           # Measures cyclomatic complexity
    - funlen           # Checks the length of functions
    - gocritic         # Detects suspicious constructs
    - gocyclo          # Measures cyclomatic complexity
    - gosimple         # Suggests code simplifications
    - stylecheck       # Checks for style issues
    - unconvert        # Removes unnecessary type conversions
    - unparam          # Finds unused function parameters
    - testifylint      # Checks for common mistakes in test code

    # Code Style
    - asciicheck       # Reports non-ASCII characters
    - dupl             # Finds code duplications
    #- gci              # Groups and sorts imports
    - gofmt            # Checks for standard formatting
    - gofumpt          # Enforces stricter formatting
    - goimports        # Manages imports organization
    - makezero         # Suggests optimized slice declarations
    - misspell         # Finds spelling mistakes
    - revive           # Linter for style and conventions
    - tagliatelle      # Ensures struct tags are consistent
    - whitespace       # Checks for inconsistent whitespace

    # Best Practices
    - gochecknoinits   # Warns about `init()` usage
    - godot            # Ensures comments end with a period
    # - goerr113         # Maintains standard error handling style
    - nonamedreturns   # Detects named return values
    #- paralleltest     # Ensures `t.Parallel()` usage in tests
    - tenv             # Warns about os.Setenv and os.Clearenv usage
    #- testpackage      # Ensures tests are in the proper package
    #- thelper          # Ensures testing helpers are named correctly

run:
  timeout: 1m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
