services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - ../../internal/sql/01_outbox_messages.up.sql:/docker-entrypoint-initdb.d/01_outbox_messages.up.sql
      - ../../internal/sql/02_users.up.sql:/docker-entrypoint-initdb.d/02_users.up.sql
      - ../../internal/sql/03_orders.up.sql:/docker-entrypoint-initdb.d/03_orders.up.sql

  localstack:
    image: localstack/localstack:4.7.0
    container_name: localstack
    environment:
      - SERVICES=sns,sqs
      - GATEWAY_LISTEN=0.0.0.0:4566
      - AWS_DEFAULT_REGION=eu-central-1
    ports:
      - "4566:4566"
    volumes:
      - ../../internal/containers/localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh
    entrypoint: [ "docker-entrypoint.sh" ]

  otel-lgtm:
    image: grafana/otel-lgtm:0.11.8
    container_name: otel-lgtm
    ports:
      - "3000:3000"  # Port for the Grafana UI
      - "4317:4317"  # OTLP gRPC port
      - "4318:4318"  # OTLP HTTP port